services:
  elasticsearch:
    image: elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=localhost
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xmx2048m -Xms2048m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash:
    image: logstash:8.15.3
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./docker/elk:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    links:
      - elasticsearch

  kibana:
    image: kibana:8.15.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    links:
      - elasticsearch

volumes:
  es_data:
